# Generated by Django 4.0.1 on 2022-05-02 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('book_image', models.ImageField(blank=True, null=True, upload_to='book_images')),
                ('categorylist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='magazine.categorieslist')),
            ],
        ),
    ]
